Update Cairo dependencies to `2.5.0`.
lambdaclass/cairo_native pull request #426
Opened 2024-01-29 10:42 UTC by azteca1998

# Update Cairo dependencies to `2.5.0`

## Description

Description of the pull request changes and motivation.

## Checklist
- [ ] Linked to Github Issue
- [ ] Unit tests added
- [ ] Integration tests added.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2024-01-29 14:37 UTC, edg-l approved these changes

2024-01-29 14:43 UTC, edg-l submitted a review, later dismissed

2024-01-31 14:57 UTC, igaray approved these changes

2024-01-31 20:14 UTC, pefontana approved these changes

2024-01-31 20:16 UTC, juanbono approved these changes

2024-01-31 20:18 UTC, juanbono commented on src/libfuncs/nullable.rs
> -    fn run_match_nullable_snapshot() {
what happened to this test?

2024-01-31 20:19 UTC, juanbono requested changes
there are 2 tests that were removed and not reimplemented anywhere

2024-01-31 20:51 UTC, juanbono approved these changes
I just saw that the 2 tests were not needed since they were for a, now deleted, libfunc.  And now we call a previously added one.

2024-02-01 11:01 UTC, merged