Bump starknet-types-core to 0.0.6
lambdaclass/cairo_native pull request #428
Opened 2024-02-05 19:16 UTC by pefontana

# Bump starknet-types-core to 0.0.6

## Description

Description of the pull request changes and motivation.

## Checklist
- [ ] Linked to Github Issue
- [ ] Unit tests added
- [ ] Integration tests added.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2024-02-12 11:35 UTC, edg-l approved these changes

2024-02-12 13:44 UTC, edg-l requested changes
you are missing the dependency on the `runtime/` folder

2024-02-15 22:19 UTC, pefontana commented
> you are missing the dependency on the `runtime/` folder

Thanks @edg-l !
Done [96ea3a3](https://github.com/lambdaclass/cairo_native/pull/428/commits/96ea3a37180a194ba14c3b21788b09e76bb634fd)

2024-02-16 11:47 UTC, azteca1998 approved these changes

2024-02-16 15:16 UTC, edg-l approved these changes

2024-02-16 23:05 UTC, merged