cairo-native-test binary
lambdaclass/cairo_native pull request #443
Opened 2024-02-20 17:02 UTC by edg-l

Fixes #442

2024-02-22 12:07 UTC, azteca1998 submitted a review, later dismissed

2024-02-22 14:05 UTC, juanbono requested changes
Please add a section in the README about how to use it

2024-02-22 14:32 UTC, edg-l commented
> Please add a section in the README about how to use it

done

2024-02-23 01:03 UTC, juanbono commented on src/executor/jit.rs
> +            gas_metadata: metadata.get::<GasMetadata>().cloned().unwrap(),
is the GasMetadata always present? if not we shouldn't have an unwrap here .

2024-02-23 01:03 UTC, juanbono commented on src/executor/aot.rs
> +            gas_metadata: metadata.remove().unwrap(),
same here

2024-02-23 01:04 UTC, juanbono approved these changes
LGTM

2024-02-23 01:05 UTC, juanbono commented on src/executor/jit.rs
> +            gas_metadata: metadata.get::<GasMetadata>().cloned().unwrap(),
It is always inserted in src/context.rs

2024-02-23 10:43 UTC, azteca1998 approved these changes

2024-02-23 11:22 UTC, merged