Fix casting libfuncs.
lambdaclass/cairo_native pull request #454
Opened 2024-02-23 14:51 UTC by azteca1998

Casting now works with `bytes31` too.

## Checklist
- [ ] Linked to Github Issue
- [ ] Unit tests added
- [ ] Integration tests added.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2024-02-23 14:53 UTC, juanbono commented on src/bin/cairo-native-test.rs
> +        JitValue::Bytes31(_) => todo!(),
why todo!()?

2024-02-23 14:54 UTC, juanbono requested changes
see comments

2024-02-23 15:11 UTC, azteca1998 commented on src/bin/cairo-native-test.rs
> +        JitValue::Bytes31(_) => todo!(),
Because it's not yet implemented.

2024-02-26 09:48 UTC, edg-l approved these changes

2024-02-26 15:54 UTC, juanbono approved these changes

2024-02-26 15:55 UTC, juanbono commented
Approving since the `todo!()` is in the testing crate and should be implemented in another PR.

2024-02-26 16:27 UTC, merged