Update bytes31 use blockext
lambdaclass/cairo_native pull request #555
Opened 2024-04-27 01:45 UTC by adrianvrj

Closes #522 

## Checklist
- [x] Linked to Github Issue
- [ ] Unit tests added
- [ ] Integration tests added.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2024-04-29 08:43 UTC, edg-l requested changes

2024-04-29 08:43 UTC, edg-l commented on src/libfuncs/bytes31.rs
> +    entry.append_op_result(helper.br(0, &[op0.result(0)?.into()], location));
you shouldn't use `append_op_result` for operations which don't have results, it was correct before. same with all the others

2024-04-29 17:28 UTC, fmoletta approved these changes

2024-04-30 09:33 UTC, edg-l approved these changes

2024-05-07 20:35 UTC, igaray approved these changes

2024-05-07 21:41 UTC, merged