test: debug info module
lambdaclass/cairo_native pull request #587
Opened 2024-05-13 17:11 UTC by greged93

Adds a unit test for DebugLocations. Adds rstest to avoid boilerplate code. Solves #486.

## Checklist
- [x] Linked to Github Issue
- [x] Unit tests added
- [ ] Integration tests added.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2024-05-14 10:59 UTC, edg-l approved these changes

2024-05-14 21:26 UTC, juanbono requested changes
Is that macro really needed?

2024-05-15 06:40 UTC, greged93 commented
The idea was just to avoid duplicate code, since both structures have the same fields. Can remove and have two asserts if you prefer

2024-05-16 13:25 UTC, azteca1998 approved these changes

2024-05-16 14:05 UTC, juanbono commented
@greged93 yes, please remove the macro as I think it makes the code more understandable

2024-05-16 17:29 UTC, juanbono approved these changes

2024-05-16 17:30 UTC, azteca1998 approved these changes

2024-05-16 18:02 UTC, igaray approved these changes

2024-05-16 18:31 UTC, merged