add docs
lambdaclass/cairo_native pull request #594
Opened 2024-05-14 13:55 UTC by edg-l

## Checklist
- [ ] Linked to Github Issue
- [ ] Unit tests added
- [ ] Integration tests added.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2024-05-14 21:36 UTC, juanbono commented on src/execution_result.rs
> +/// This module contains the structures used to interprete the program execution results, either
typo: interprete -> interpret

2024-05-14 21:41 UTC, juanbono approved these changes

2024-05-14 21:42 UTC, juanbono requested changes
check typos

2024-05-16 13:22 UTC, azteca1998 submitted a review, later dismissed

2024-05-16 14:09 UTC, juanbono approved these changes

2024-05-17 01:29 UTC, juanbono commented
Please fix conflicts @edg-l

2024-05-17 09:30 UTC, edg-l commented
> Please fix conflicts @edg-l

done

2024-05-17 13:42 UTC, juanbono approved these changes

2024-05-17 14:22 UTC, merged