Implement coupon libfuncs
lambdaclass/cairo_native pull request #621
Opened 2024-05-23 11:12 UTC by edg-l

Depends on #620

Closes #494

I can't add tests because it's a experimental feature and requires configuring the cairo-tests with the new edition, which breaks lot of imports, and would need to restructure the cairo-test code. But i tested it in a isolated way and it works.

## Checklist
- [ ] Linked to Github Issue
- [ ] Unit tests added
- [ ] Integration tests added.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2024-05-24 15:35 UTC, juanbono approved these changes

2024-05-30 10:18 UTC, edg-l commented
superseded by  #622

2024-06-04 11:32 UTC, igaray requested changes

2024-06-04 11:32 UTC, igaray commented on src/libfuncs/coupon.rs
> +/// Generate MLIR operations for the `coupon` libfunc.
Can you add some short documentation explaining
- what the coupon libfunc does and how it is supposed to work, and
- how the builder implements said logic

2024-06-04 14:37 UTC, igaray submitted a review, later dismissed

2024-06-04 14:39 UTC, juanbono approved these changes

2024-06-04 19:27 UTC, juanbono approved these changes

2024-06-04 19:31 UTC, pefontana approved these changes

2024-06-04 20:56 UTC, merged