add scarb-native-dump
lambdaclass/cairo_native pull request #642
Opened 2024-06-03 14:15 UTC by edg-l

## Checklist
- [ ] Linked to Github Issue
- [ ] Unit tests added
- [ ] Integration tests added.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2024-06-03 14:27 UTC, juanbono requested changes
Please add docs about how to use this new bin

2024-06-03 14:40 UTC, edg-l commented
> Please add docs about how to use this new bin and examples.

done!

2024-06-03 15:31 UTC, juanbono submitted a review, later dismissed

2024-06-04 11:34 UTC, igaray approved these changes

2024-06-04 11:58 UTC, juanbono approved these changes

2024-06-04 12:54 UTC, merged