Fix the starknet libfuncs' bugs.
lambdaclass/cairo_native pull request #694
Opened 2024-06-20 17:26 UTC by azteca1998

## Checklist
- [ ] Linked to Github Issue
- [ ] Unit tests added
- [ ] Integration tests added.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2024-06-24 12:52 UTC, igaray approved these changes

2024-06-24 14:29 UTC, Oppen requested changes
At a very high level I suspect this PR is OK in content. But it is hard to review due to it's size.

My suggestion: cherry-pick the actual fixes to a different one, let's merge that one, and only then rebase this to the fixed main as a proper refactor (and refactor only) PR that we can review calmly without pressure to merge quickly.

2024-09-20 15:00 UTC, edg-l approved these changes

2024-09-20 15:45 UTC, Oppen approved these changes

2024-09-20 16:15 UTC, merged