Remove memory leak on invoke arena
lambdaclass/cairo_native pull request #725
Opened 2024-07-09 10:25 UTC by edg-l

## Checklist
- [ ] Linked to Github Issue
- [ ] Unit tests added
- [ ] Integration tests added.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2024-07-09 15:36 UTC, azteca1998 approved these changes

2024-07-09 17:21 UTC, pefontana requested changes
Can we add a test, to replicate the bug?

2024-07-10 11:47 UTC, edg-l commented
> Can we add a test to replicate the bug? Or why are we adding this?

We are not adding anything we are removing it. It was a hack to fix a segfault before and now its needed, no segfault happens without the line.

2024-07-10 11:49 UTC, juanbono approved these changes

2024-07-10 11:53 UTC, pefontana approved these changes

2024-07-10 12:48 UTC, merged