Add lldb tutorial
lambdaclass/cairo_native pull request #760
Opened 2024-08-14 21:12 UTC by JulianGCalderon

Adds a tutorial on debugging with lldb

2024-08-15 20:21 UTC, pefontana requested changes
Good Doc @JulianGCalderon !

2024-08-15 20:21 UTC, pefontana commented on README.md
> +To debug with LLDB (or another debugger), we must compile the program with the `with-debug-utils` feature.
```suggestion
To debug with LLDB (or another debugger), we must compile the binary with the `with-debug-utils` feature.
```

2024-08-15 20:21 UTC, pefontana commented on README.md
> +lldb -- target/debug/cairo-native-run -s debug.cairo --run-mode aot
```suggestion
lldb -- target/debug/cairo-native-run -s programs/recursion.cairo --available-gas 99999999 --run-mode aot
```

2024-08-19 19:14 UTC, igaray approved these changes

2024-08-19 19:22 UTC, pefontana approved these changes

2024-08-19 20:05 UTC, merged