Implement libfunc profiler.
lambdaclass/cairo_native pull request #946
Opened 2024-11-27 23:26 UTC by azteca1998

Implementation of a libfunc profiler for the `x86_64` architecture (for now).

For each executed libfunc, generates:
  - Number of samples.
  - Total number of ticks.
  - Average number of ticks.
  - Standard deviation.
  - Quartiles (0%, 25%, 50%, 75%, 100%).

Also implements an outlier detection system to filter out operating system noise.

## Checklist
- [ ] Linked to Github Issue
- [ ] Unit tests added
- [ ] Integration tests added.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2025-06-02 15:25 UTC, gabrielbosio commented on src/bin/cairo-native-run.rs
> +    /// The output path for the libfunc profilling results
```suggestion
    /// The output path for the libfunc profiling results
```

2025-06-02 15:32 UTC, JulianGCalderon commented on src/bin/cairo-native-run.rs
> +        }
Could you write the output of an example run in the description of the PR?

2025-06-02 15:34 UTC, JulianGCalderon commented on src/compiler.rs
> -                    };
Why was this instruction moved?

2025-06-02 15:36 UTC, JulianGCalderon commented on src/compiler.rs
> +                                // Tail-recursive function calls are broken. Also it'd include the entire function which
> Tail-recursive function calls are broken

What does this mean?

2025-06-02 15:41 UTC, JulianGCalderon commented on src/metadata/profiler.rs
> +        Ok((value, core_idx))
What is `core_idx`? Could you add documentation on the return values?

2025-06-02 15:43 UTC, JulianGCalderon commented on src/metadata/profiler.rs
> +    pub fn measure_timestamp<'c, 'a>(
If the profiling for aarch64 is not accurate, maybe we should we disable it entirely?

2025-06-02 15:45 UTC, JulianGCalderon commented on src/metadata/profiler.rs
> +    }
Could you document that u64::MAX implies an invalid time delta?

2025-06-02 15:47 UTC, JulianGCalderon commented on src/libfuncs.rs
> +        block.append_operation(cf::br(successor, &destination_operands, location));
Why do we now append the operation, rather than just returning the `cf::br` operation? Idem for `cond_br`.

2025-06-02 18:31 UTC, FrancoGiachetta commented on src/compiler.rs
> +                                // Tail-recursive function calls are broken. Also it'd include the entire function which
Added better docs here

2025-06-02 18:32 UTC, FrancoGiachetta commented on src/metadata/profiler.rs
> +    }
Done

2025-06-02 18:33 UTC, FrancoGiachetta commented on src/libfuncs.rs
> +        block.append_operation(cf::br(successor, &destination_operands, location));
We concluded this would be quite difficult to accomplish.

2025-06-02 20:02 UTC, FrancoGiachetta commented on src/bin/cairo-native-run.rs
> +        }
Done

2025-06-05 16:11 UTC, FrancoGiachetta commented on src/compiler.rs
> -                    };
the new `LibfuncHelper`'s initilization adds this `match` statement: 
```rust
#[cfg(feature = "with-libfunc-profiling")]
    profiler: match libfunc {
        CoreConcreteLibfunc::FunctionCall(_) => {
        // Tail-recursive function calls are broken. Also it'd include the entire function which
        // doesn't make sense, therefore it's ignored on purpose.
           None
       }
       _ => match metadata.remove::<crate::metadata::profiler::ProfilerMeta>()
           {
               Some(profiler_meta) => {
                   let t0 = profiler_meta
                       .measure_timestamp(context, block, location)?;
                   Some((profiler_meta, statement_idx, t0))
               }
               None => None,
            },
    }
```
Which makes use of libfunc, a variable declared after the old initialization.

2025-06-10 16:09 UTC, FrancoGiachetta commented on src/metadata/profiler.rs
> +        Ok((value, core_idx))
Added documentation about the return values

2025-06-10 16:16 UTC, FrancoGiachetta commented on src/metadata/profiler.rs
> +    pub fn measure_timestamp<'c, 'a>(
It seems this is not as inaccurate as we thought, so perhaps it is safe to leave it as it is.

2025-06-10 18:27 UTC, JulianGCalderon commented on programs/examples/brainfuck.cairo
Why was this example changed?

2025-06-10 18:29 UTC, JulianGCalderon commented on src/compiler.rs
> +                                // doesn't make sense to function calls into account, therefore it's ignored on purpose.
```suggestion
                                // doesn't make sense to take function calls into account, therefore it's ignored on purpose.
```

2025-06-10 18:39 UTC, JulianGCalderon commented on src/libfuncs.rs
> +    )>,
Could you add a comment explaining what does `None` mean?

2025-06-10 18:42 UTC, JulianGCalderon commented on src/metadata/profiler.rs
> +    _private: (),
What does the field `_private` mean?

2025-06-10 18:47 UTC, JulianGCalderon commented on src/metadata/profiler.rs
> +    TraceId,
This should be called `ProfileId`.

```suggestion
    ProfileId,
```

2025-06-10 18:48 UTC, JulianGCalderon commented on src/metadata/profiler.rs
> +        // invalid data
Can you move this to the function documentation? That way its easier to find. Please also add it to the aarch64 function.

2025-06-10 18:53 UTC, JulianGCalderon commented on src/metadata/profiler.rs
> +    /// Receives two timestamps, if they were originated in the same statement index
> if they were originated in the same statement index

Were is this condition being checked?

2025-06-10 18:55 UTC, JulianGCalderon commented on src/metadata/profiler.rs
> +        t1: (Value<'c, '_>, Value<'c, '_>),
Could you add the meaning of this field in this function signature also?

2025-06-10 19:03 UTC, JulianGCalderon commented on src/metadata/profiler.rs
> +        }
I think its better to separate the profile processing, from profile capturing.

We could move this method to a standalone function that receives:
1. The raw profile data
2. The sierra program.

And builds the sierra profile summary. I'd also move the definition from the Sequencer into Native:

```rust
pub struct LibfuncProfileSummary {
    pub libfunc_idx: ConcreteLibfuncId,
    pub samples: u64,
    pub total_time: u64,
    pub average_time: f64,
    pub std_deviation: f64,
    pub quartiles: [u64; 5],
}
```

And have something like the following function for processing.

```rust
fn summarize_profile(program: &Program, profile_data: &[StatementIdx, u64]) -> Vec<LibfuncProfileSummary>;
```

We can then call this from Sequencer / cairo-native-run.

2025-06-10 19:13 UTC, FrancoGiachetta commented on programs/examples/brainfuck.cairo
This was done due to deprecations. We import the trait instead of the method is self

2025-06-10 19:21 UTC, JulianGCalderon commented on programs/examples/brainfuck.cairo
Oh I see, is it because we updated Cargo lock? I think its not necessary to update the Cargo lock in this PR.

2025-06-10 19:37 UTC, FrancoGiachetta commented on src/metadata/profiler.rs
> +    /// Receives two timestamps, if they were originated in the same statement index
Mmm, actually is a bit confusing. If both timestamps weren't calculated in the same CPU core, then the delta time would not be valid. I'll the docs

2025-06-10 20:25 UTC, FrancoGiachetta commented on src/metadata/profiler.rs
> +        }
I could split the processing into two method the avoid having such a large one. But I don't why we should have method with that signature. What would be it's benefit?

2025-06-10 20:33 UTC, JulianGCalderon commented on src/metadata/profiler.rs
> +        }
The main benefit would be to separate concerns. The user of the library can choose how to process the samples, and we just provide a helper function for summarizing the data. We don't need to tie the processing of the samples to the capturing of them.

Also, I doesn't need to be a method. It would be a standalone function.

The other benefit would be to remove `program` from `ProfileImpl`, as its only used for processing.

2025-06-10 20:52 UTC, FrancoGiachetta commented on src/metadata/profiler.rs
> +        }
I see you point. However being the pass a `Program` as a parameter would mean that you can pass any `Program`, which could lead to incorrect results. Having the Program "attach" ensures this won't happen. Would receiving a closure as a parameter work?

2025-06-10 21:08 UTC, FrancoGiachetta commented on programs/examples/brainfuck.cairo
No, it was due to the cairo's corelib

2025-06-10 21:09 UTC, FrancoGiachetta commented on src/libfuncs.rs
> +    )>,
Done

2025-06-10 21:09 UTC, FrancoGiachetta commented on src/metadata/profiler.rs
> +    TraceId,
Done

2025-06-10 21:09 UTC, FrancoGiachetta commented on src/metadata/profiler.rs
> +        // invalid data
Done

2025-06-10 21:09 UTC, FrancoGiachetta commented on src/metadata/profiler.rs
> +    /// Receives two timestamps, if they were originated in the same statement index
Done

2025-06-10 21:09 UTC, FrancoGiachetta commented on src/metadata/profiler.rs
> +        t1: (Value<'c, '_>, Value<'c, '_>),
Done

2025-06-10 21:17 UTC, JulianGCalderon commented on src/metadata/profiler.rs
> +        }
What do you mean by a closure?

2025-06-10 21:51 UTC, FrancoGiachetta commented on src/metadata/profiler.rs
> +        }
An anonymous function defined by the user to process the profiles.

2025-06-11 12:36 UTC, FrancoGiachetta commented on src/metadata/profiler.rs
> +    _private: (),
I think it was simply to avoid constructing the struct directly. However I think it is useless now since is has another private field. I'll change it

2025-06-11 17:19 UTC, JulianGCalderon commented on src/metadata/profiler.rs
> +        }
I think this design debate is subjective. I don't want to block on this. We can leave it as is, or seek an external opinion. 

Regardless. I don't see any benefit for defining a closure for processing the raw data, instead of exposing the raw data to the user directly. Both achieve the same result, but the closure approach adds unnecessary complexity IMO.

I think something like the following is simpler:

```rust
pub struct ProfilerImpl {}

impl ProfilerImpl {
  pub fn get_profile(&self) -> Profile;
}

type Profile = Vec<Sample>;
pub struct Sample {
  pub statement: StatementIdx,
  pub measure: SampleMeasure,
}
pub enum SampleMeasure {
  DeltaNs(u128),
  Unit,
}
```

This way we just provide a way for accessing the whole program profile, allowing us to:
- Calculate statistics for a libfunc (avg, mean, dev).
- Calculate distribution of a libfunc (does it always take X time, or its execution time varies a lot).
- As we don't aggregate results prematurely, we also have information on the order that this samples were recorded. Note that if we group by libfunc we lose this information.

If its something we do very often, we can also provide a helper for calculating the summary:

```rust
pub struct LibfuncProfileSummary {
    pub libfunc_idx: ConcreteLibfuncId,
    pub samples: u64,
    pub total_time: u64,
    pub average_time: f64,
    pub std_deviation: f64,
    pub quartiles: [u64; 5],
}

impl Profile {
    pub fn summarize(&self, program: &Program) -> Vec<LibfuncProfileSummary>;
}
```

> However being able to pass a Program as a parameter would mean that you can pass any Program, which could lead to incorrect results.

True, but the current solution does not tackle this. The type `ConcreteLibfuncId` depends on the program registry. For the user to correctly inspect that libfunc, it needs the registry of the program. Also, the user needs to create `ProfilerImpl` at the start of the execution, an can also use the wrong `Program`.

2025-06-12 12:36 UTC, FrancoGiachetta commented on src/metadata/profiler.rs
> +        }
In my opinion it would be simpler to allow the user to pass the function in charge of processing the data. It has all the benefits you mentioned. If the objective would be to get the raw data, the closure would just return it without changing it all. Thus, we don't need to define any other structs, types or methods. However, I'm open to an external opinion.

2025-06-12 16:10 UTC, gabrielbosio commented on src/metadata/profiler.rs
> +    pub fn measure_timestamp<'c, 'a>(
What does "as inaccurate as we thought" means in this case? Is it usable?

2025-06-12 16:43 UTC, gabrielbosio commented on src/metadata/profiler.rs
> +        }
If processing is something it is done at the end of the `summarize_profiles` we can separate that function in two parts. That way we remove the need of using a closure. The flow would look like this:

1. The user calls `summarize_profiles`. It returns a value.
2. The user does something with that returned value.

I think it is simpler than:

1. The user implements a closure that receives a value that will be processed by `summarize_profiles` in some way.
2. The user calls `summarize_profiles` passing that closure as an argument. It returns a value dependent of the user-defined closure.

Maybe it is because I like to think data flow more linearly. Maybe a closure would be necessary if the processing is being done in the middle of the `summarize_profiles` function (Being the `processor` a hook in that case).

2025-06-12 16:45 UTC, gabrielbosio commented on src/metadata/profiler.rs
> +        }
It is true that the complexity is being moved to the creation of other structs. Still I prefer to think this more linearly in this case.

2025-06-12 17:08 UTC, FrancoGiachetta commented on src/metadata/profiler.rs
> +        }
Okay, I'll change it then. It should't require to add additional structs.

2025-06-12 17:59 UTC, JulianGCalderon commented on src/metadata/profiler.rs
> +        }
> If processing is something it is done at the end of the summarize_profiles

Not necessarily. Summarizing the profiles by calculating the average is just one way of processing the raw profile data. An alternative way would be to, for example, plot a histogram of the execution time of a particular libfunc. The output of `summarize_profiles` would not be sufficient for calculating that histogram, and we would need the whole raw data.

2025-06-12 18:08 UTC, JulianGCalderon commented on src/metadata/profiler.rs
> +        }
In order words, there are two different elements:

- The raw samples: It contains a list of statements and their delta time (or an unit value if no delta time was calculated).
- A statistical summary: It contains for each libfunc, some aggregated data (average, std. dev., etc.).

The statistical summary can be derived from the raw samples.

Then, there are two alternatives for calculating a statistical summary:
- A process closure that receives a preprocessed representation of the raw profile data.
- A getter function that returns the raw profile data, which is later processed by the user.

2025-06-12 18:20 UTC, FrancoGiachetta commented on src/metadata/profiler.rs
> +        }
Sorry, I'm starting to think this is more of a problem of misunderstandings. To clarify my point of view, I see `summarize_profiles` as method which should output the data ready to be analyzed. This is why I suggested a closure since I don't see any use for raw data, and this is kind of a way of implying the processing.

2025-06-12 18:31 UTC, FrancoGiachetta commented on src/metadata/profiler.rs
> +        }
I've removed the closure and the `sierra_program` from the `ProfileImpl` struct. Now `get_profiles` returns the raw_data.

2025-06-12 19:09 UTC, JulianGCalderon commented on programs/examples/brainfuck.cairo
If this change is unrelated to the current PR, I'd revert this change and we can fix it in another PR.

2025-06-12 19:10 UTC, JulianGCalderon commented on Cargo.lock
This PR doesn't change the Cargo.toml. Why did the Cargo.lock changed? If its unrelated, could you revert it?

2025-06-12 19:15 UTC, JulianGCalderon commented on src/metadata/profiler.rs
> +//!    from that, it will count every libfunc's call, allowing to summarize every libfun'c execution execution time.
```suggestion
//! 2. `push_frame`: called before every branching operation. This method will also call `measure_timestamp`. This,
//!    with the timestamp calculated before the execution, will allow to measure each statement's execution time.
//!    If for some reason, the statement delta time could not be gathered, we just record an unit value, recording that
//!    we executed the given statement.
```

2025-06-12 19:16 UTC, JulianGCalderon commented on src/metadata/profiler.rs
> +//! exepects a closure to process this information.
```suggestion
//! Once the program execution finished and the information was gathered, the `get_profile` method can be called.
//! It groups the samples by libfunc, and returns all data related to each libfunc.
```

2025-06-12 19:16 UTC, JulianGCalderon commented on src/metadata/profiler.rs
> +//! As well as with the trace-dump fature, in the context of starknet contracts, we need to add support for building
```suggestion
//! As well as with the trace-dump feature, in the context of Starknet contracts, we need to add support for building
```

2025-06-12 19:16 UTC, JulianGCalderon commented on src/metadata/profiler.rs
> +//! profiles for multiple programs. To do so, we need two important elements, which must be set before every contract
```suggestion
//! profiles for multiple executions. To do so, we need two important elements, which must be set before every contract
```

2025-06-12 19:17 UTC, JulianGCalderon commented on src/metadata/profiler.rs
> +//! 1. A glbal static hashmap to map every profile id to its respective profile summary. See `LIBFUNC_PROFILE`.
```suggestion
//! 1. A global static hashmap to map every profile ID to its respective profiler. See `LIBFUNC_PROFILE`.
```

2025-06-12 19:18 UTC, JulianGCalderon commented on src/metadata/profiler.rs
> +//! 2. A counter to track the ID of the current libfunc profile, which gets updated every time we switch to another
```suggestion
//! 2. A counter to track the ID of the current profiler, which gets updated every time we switch to another
```

2025-06-12 19:19 UTC, JulianGCalderon commented on src/metadata/profiler.rs
> +#[cfg(feature = "with-libfunc-profiling")]
This feature gate should not be required, as this file is gated entirely.

2025-06-12 19:20 UTC, JulianGCalderon commented on src/metadata/profiler.rs
> +    /// Values
```suggestion
    /// Gets the current timestamp.
    ///
    /// The values returned are:
```

2025-06-12 19:20 UTC, JulianGCalderon commented on src/metadata/profiler.rs
> +    /// Values
/// Gets the current timestamp.
    ///
    /// The values returned are:

2025-06-12 19:21 UTC, JulianGCalderon commented on src/metadata/profiler.rs
> +    ///
Please add a comment in the function signature, explaining that the core idx cannot be retreived in aarch64, and therefore we always return the same value: `0`.

2025-06-12 19:26 UTC, JulianGCalderon commented on src/metadata/profiler.rs
> +pub type LibfuncProfiles = HashMap<ConcreteLibfuncId, (Vec<u64>, u64)>;
Please change the tuple for a structure:

```rust
/// Represents the entire profile of the execution.
///
///It maps the libfunc ID to a libfunc profile.
type Profile = HashMap<ConcreteLibfuncId, LibfuncProfileData)>;

/// Represents the profile data for a particular libfunc.
struct LibfuncProfileData {
    /// A vector of execution times, for each time the libfunc was executed.
    deltas: Vec<u64>,
    /// If the time delta for a particular execution could not be gathered,
    /// we just increase `extra_counts` by 1.
    extra_counts: u64,
}
```

2025-06-12 19:26 UTC, JulianGCalderon commented on src/metadata/profiler.rs
> +pub type LibfuncProfiles = HashMap<ConcreteLibfuncId, (Vec<u64>, u64)>;
Also, document what is the unit of the deltas vector. Is it in nanoseconds?

2025-06-12 19:27 UTC, JulianGCalderon commented on src/metadata/profiler.rs
> +pub struct ProfileImpl {
```suggestion
pub struct ProfilerImpl {
```

2025-06-12 19:28 UTC, JulianGCalderon commented on src/metadata/profiler.rs
> +    ///
This comments are outdated. I think they could be removed. If we document de data type correctly, there is no need to repeat the meaning of the fields here.

2025-06-12 19:30 UTC, JulianGCalderon commented on src/metadata/profiler.rs
> +    pub trace: Vec<(StatementIdx, u64)>,
```suggestion
    /// The samples recorded by the profiler. A value of `u64::MAX` implies
    /// that the delta time for a statement could not be gathered.
    pub samples: Vec<(StatementIdx, u64)>,
```

2025-06-12 19:31 UTC, JulianGCalderon commented on src/metadata/profiler.rs
> +    /// Process profiling results.
I'd rename this comment to: "Returns the execution profile, grouped by libfunc".

2025-06-12 19:34 UTC, JulianGCalderon commented on src/metadata/profiler.rs
> +    pub fn get_profiles(&self, sierra_program: &Program) -> LibfuncProfiles {
Its clearer to refer to the full profile as `Profile` directly.

```suggestion
    pub fn get_profile(&self, sierra_program: &Program) -> Profile {
```

2025-06-12 19:38 UTC, FrancoGiachetta commented on src/metadata/profiler.rs
> +    pub fn get_profiles(&self, sierra_program: &Program) -> LibfuncProfiles {
Mmm, I saw a profile a profile as an individual Libfunc. But I'll change it if you prefer

2025-06-12 19:43 UTC, JulianGCalderon commented on src/metadata/profiler.rs
> +    pub fn get_profiles(&self, sierra_program: &Program) -> LibfuncProfiles {
I can be though as both ways, but using `Profile` for the whole execution profile seems consistent with other profilers (like Samply)

2025-06-12 20:43 UTC, FrancoGiachetta commented on src/metadata/profiler.rs
> +pub type LibfuncProfiles = HashMap<ConcreteLibfuncId, (Vec<u64>, u64)>;
It's measured in cpu cycles. I added that the the comment.

2025-06-12 20:43 UTC, FrancoGiachetta commented
All comments were resolved

2025-06-12 21:37 UTC, JulianGCalderon requested changes

2025-06-12 21:37 UTC, JulianGCalderon commented on src/bin/cairo-native-run.rs
> +            let mut processed_profiles = process_profiles(raw_profiles);
To keep consistency, we should use the singular here `raw_profile`, `processed_profile`, etc.

2025-06-12 21:37 UTC, JulianGCalderon commented on src/metadata/profiler.rs
> +//! 1. A golbal static hashmap to map every profile ID to its respective profiler. See `LIBFUNC_PROFILE`.
```suggestion
//! 1. A global static hashmap to map every profile ID to its respective profiler. See `LIBFUNC_PROFILE`.
```

2025-06-12 21:37 UTC, JulianGCalderon commented on src/metadata/profiler.rs
> +//!    contract. Since a contract can call other contract's, we need a way of restoring the counter after every execution.
```suggestion
//!    contract. Since a contract can call other contracts, we need a way of restoring the counter after every execution.
```

2025-06-12 21:37 UTC, JulianGCalderon commented on src/metadata/profiler.rs
> +    ///    In case of arm, 0 is always return as there's no way to know in which
```suggestion
    ///    In case of arm, 0 is always returned as there's no way to know in which
```

2025-06-12 21:37 UTC, JulianGCalderon commented on src/metadata/profiler.rs
> +    ///    In case of arm, 0 is always return as there's no way to know in which
```suggestion
    ///    In case of arm, 0 is always returned as there's no way to know in which
```

2025-06-12 21:37 UTC, JulianGCalderon commented on src/metadata/profiler.rs
> +/// couldn't be calculated.
This comment is outdated.

2025-06-12 21:37 UTC, JulianGCalderon commented on src/metadata/profiler.rs
> +///It maps the libfunc ID to a libfunc profile.
```suggestion
/// It maps the libfunc ID to a libfunc profile.
```

2025-06-13 14:28 UTC, FrancoGiachetta commented on src/metadata/profiler.rs
> +    pub fn measure_timestamp<'c, 'a>(
It is usable but there's a possibility that there could be noise in the results, which is not the case in x86.

2025-06-13 15:30 UTC, JulianGCalderon commented on src/bin/cairo-native-run.rs
> +    pub quartiles: Option<[u64; 5]>,
In which situation do we return `None`?

2025-06-13 15:30 UTC, JulianGCalderon commented on src/bin/cairo-native-run.rs
> +            let mut processed_profile = process_profiles(raw_profile);
```suggestion
            let mut processed_profile = process_profile(raw_profile);
```

2025-06-13 15:30 UTC, JulianGCalderon commented on src/bin/cairo-native-run.rs
> +                };
If only a single field is `None`, this will write `None` in all of them.

2025-06-13 15:30 UTC, JulianGCalderon commented on src/bin/cairo-native-run.rs
> +                // Compuite the average.
```suggestion
                // Compute the average.
```

2025-06-13 15:30 UTC, JulianGCalderon commented on src/metadata/profiler.rs
> +//!  1. `measure_timestamp`: called before every libfunc execution.
```suggestion
//! 1. `measure_timestamp`: called before every libfunc execution.
```

2025-06-13 15:33 UTC, FrancoGiachetta commented on src/bin/cairo-native-run.rs
> +    pub quartiles: Option<[u64; 5]>,
In x86, if a libfunc is call once and the timestamps calculated are invalid, then `deltas` will be an empty array.

2025-06-13 15:36 UTC, FrancoGiachetta commented on src/bin/cairo-native-run.rs
> +                };
Yes, but I would need to unwrap the rest anyway.

2025-06-13 18:51 UTC, JulianGCalderon commented on src/bin/cairo-native-run.rs
> +    pub quartiles: Option<[u64; 5]>,
I could not find that logic in the code. It seems to never use `None`.

2025-06-13 18:51 UTC, JulianGCalderon commented on src/bin/cairo-native-run.rs
> +                };
Wouldn't it be better to check each of them individually? Or it doesn't matter?

2025-06-13 19:09 UTC, FrancoGiachetta commented on src/bin/cairo-native-run.rs
> +                };
I prefer doing it in one line. I don't want it to panic if no deltas were calculated, so unwrapping is not an option. Checking each value individually would mean I would need to tackle the `None` case for each of them. I think it's simpler and cleaner to leave it in one line.

2025-06-13 19:20 UTC, FrancoGiachetta commented on src/bin/cairo-native-run.rs
> +    pub quartiles: Option<[u64; 5]>,
You are, I mess up and used `Some(..)` instead. Fixed it

2025-06-13 19:51 UTC, JulianGCalderon commented on src/bin/cairo-native-run.rs
> +                };
If its impossible for one value to be None, but for the other values to be Some, then  We **should** check each value individually. If its not possible for this to happen (either all are None, or all are Some) then we could leave it this way.

2025-06-13 19:53 UTC, JulianGCalderon approved these changes
LGTM

2025-06-13 19:53 UTC, FrancoGiachetta commented on src/bin/cairo-native-run.rs
> +                };
All this values depend on the fact that `deltas` is not empty. So it is not.

2025-06-17 14:43 UTC, JulianGCalderon commented
These changes were squashed in #1253.

2025-06-17 14:43 UTC, closed without merging